---
- name: Reiniciar Nginx
  debug:
    msg: "Comprobando la configuración primero"
  changed_when: True
  notify:
    - Comprobar config Nginx
    - Reiniciar Nginx post config

- name: Recargar Nginx
  debug:
    msg: "Comprobando la configuración primero"
  changed_when: True
  notify:
    - Comprobar config Nginx
    - Recargar Nginx post config

- name: Comprobar config Nginx
  command: "{{ nginx_ejecutable }} -t"
  register: resultado
  changed_when: "resultado.rc != 0"
  check_mode: no

- name: Reiniciar Nginx post config
  service:
    name: "{{ nginx_nombre_servicio }}"
    state: restarted

- name: Recargar Nginx post config
  service:
    name: "{{ nginx_nombre_servicio }}"
    state: reloaded
